# Numpy

The Numpy library is the core library for scientific computing in python.
It provides a high-performance multidimensional array object, and tools for working with these arrays

In [1]:
#importing  numpy package
import numpy as np

In [2]:
#creating arrays
a=np.array([1,2,3])
b=np.array([(1.5,2,3),(4,5,6)],dtype=float)
c=np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]],dtype=float)

### Initial placeholders


In [5]:
#array of zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
#array of ones
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [7]:
#Array of evenly spaced values
#step value
d=np.arange(10,25,5)
d

array([10, 15, 20])

In [8]:
#Array of evenly spaced values
#number of samples
np.linspace(10,25,5)

array([10.  , 13.75, 17.5 , 21.25, 25.  ])