# Numpy

The Numpy library is the core library for scientific computing in python.
It provides a high-performance multidimensional array object, and tools for working with these arrays

In [1]:
#importing  numpy package
import numpy as np

In [2]:
#creating arrays
a=np.array([1,2,3])
b=np.array([(1.5,2,3),(4,5,6)],dtype=float)
c=np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]],dtype=float)

## Initial placeholders


In [3]:
#array of zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
#array of ones
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [5]:
#Array of evenly spaced values
#step value
d=np.arange(10,25,5)
d

array([10, 15, 20])

In [6]:
#Array of evenly spaced values
#number of samples
np.linspace(10,25,5)

array([10.  , 13.75, 17.5 , 21.25, 25.  ])

In [7]:
#create a comstant array
e=np.full((2,2),7)
e

array([[7, 7],
       [7, 7]])

In [8]:
#create a 2x2 identity matrix
f=np.eye(2)
#create a 3x3 identity matrix
f1=np.eye(3)

In [9]:
#creating an array with random values
np.random.random((2,2))

array([[0.32680558, 0.92119967],
       [0.20687289, 0.85517712]])

In [10]:
#creating an empty array
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

##Input And Output

In [11]:
#saving and loading arrays on Disk
np.save('/my_array.npy',a)
#saving in npz format
np.savez('/array.npz',a,b)
#loading the arrays from file
s=np.load('/my_array.npy')
s


array([1, 2, 3])

In [12]:
#saving and loading text files
l=np.loadtxt("D:/project/packages/myfile.txt")
gn=np.genfromtxt("D:/project/packages/my_file.csv",delimiter=',')
sv=np.savetxt("D:/project/packages/myarray.txt",a,delimiter=" ")

##Data Types

In [13]:
np.int64 #signed 64-bit integer types
np.float32 #Standard double-precision floating point
np.complex #complex  numbers represented by 128 floats
np.bool #Boolean type storing TRUE and FALSE values
np.object #python object type
np.string_ #Fixed -length string type
np.unicode_ #Fixed - length unicode type

numpy.str_

# Inspecting Your Array

In [14]:
#array dimensions
a.shape

(3,)

In [15]:
#length of array
len(a)

3

In [16]:
#Number of arrau=y Dimensions
b.ndim

2

In [17]:
#Number of array elements
e.size

4

In [18]:
#Data type of array elements
b.dtype

dtype('float64')

In [19]:
#Name of datatype
b.dtype.name

'float64'

In [20]:
#convert an array to a different type
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
#Asking for Help
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


##Array Mathematics
###Arithmetic operations

In [22]:
#subtraction
g=a-b
np.subtract(a,b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [23]:
#Addition
ad=b+a
np.add(b,a)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [24]:
#Division
dv=a/b
np.divide(a,b)

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [25]:
#Multiplication
ml=a*b
np.multiply(a,b)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [26]:
#Exponentiation
np.exp(b)

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [27]:
#Square root
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [28]:
#sines of array
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [29]:
#element wise cosine
np.cos(b)

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [30]:
##element wise natural logarithm
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [31]:
#Dot product
e.dot(f)

array([[7., 7.],
       [7., 7.]])

In [32]:
#Comparison
a==b

array([[False,  True,  True],
       [False, False, False]])

In [33]:
a<2

array([ True, False, False])

##Aggregate Functions


In [34]:
#Array wise sum
a.sum()

6

In [35]:
#Array wise minimum value
a.min()

1

In [36]:
#maximum value of an array row
b.max(axis=0)

array([4., 5., 6.])

In [37]:
#cummulative sum of the elements
b.cumsum(axis=1)

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [38]:
#mean
a.mean()

2.0

In [39]:
#correlation coefficient
np.corrcoef(a)

1.0

In [41]:
#standard deviation
np.std(b)

1.5920810978785667

##Copying Arrays

In [43]:
#create a view of the array with the same data
h=a.view()
h

array([1, 2, 3])

In [44]:
#create a copy of the array
np.copy(a)

array([1, 2, 3])

In [45]:
#create a deep copy of the array
h=a.copy()

##Sorting Arrays

In [47]:
#sort an array
a.sort()
a

array([1, 2, 3])

In [49]:
#sort the elements of an arrays axis
c.sort(axis=0)
c

array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])

In [50]:
#subsetting
#selecting the element at 2nd index
a[2]

3

In [51]:
#selecting the element at row 0 to column 2(equivalent to b[1][2])
b[1,2]

6.0

##Slicing

In [52]:
#select items at index 0 to 1
a[0:2]

array([1, 2])

In [54]:
#select items rows o and 1 in column 1
b[0:2,1]

array([2., 5.])

In [56]:
#select all items at row 0 (equivalent to b[0:1,:1])
b[:1]

array([[1.5, 2. , 3. ]])

In [57]:
#same as [1,:,:]
c[1,...]

array([[3., 2., 3.],
       [4., 5., 6.]])

In [58]:
#reversed array
a[::-1]

array([3, 2, 1])

In [59]:
#Boolean Indexing
a[a<2]

array([1])

In [60]:
#Fancy Indexing
#select elements (1,0),(0,1),(1,2) and (0,0)
b[[1,0,1,0],[0,1,2,0]]

array([4. , 2. , 6. , 1.5])

In [62]:
#sellect a subset of the matrixs rows and columns
b[[1,0,1,0]][:,[0,1,2,0]]

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

##Arrray Manipulation

In [63]:
#Transposing Array
#permute array dimensions
i=np.transpose(b)
i.T

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [64]:
#Changing Array Shape
#Flatten the array
b.ravel()

array([1.5, 2. , 3. , 4. , 5. , 6. ])